#!/bin/bash
if [ $# -lt 2 ]; then
    echo "Usage: `basename $0` image app [app2 ...]"
    exit 1
fi

IMG=$1
shift
APP=($@)
TMP=$(mktemp)

echo $TMP

for i in ${APP[@]}; do
    docker run --rm --entrypoint bash $IMG ldd $i | awk '{
        if (NF<3)
            printf "%s\n", $1
        else
            printf "%s\n", $3
    }'
done >>$TMP

sort $TMP | uniq
rm $TMP
