#!/bin/bash
#
# find intersection of N groups
# Ruoshi Sun
# 2020-10-26: N groups
# 2019-12-10: 2 groups

function print_usage {
    echo "Usage: `basename $0` [-v] GROUP1 GROUP2 [GROUP3 ...]"
    echo "-v   verbose"
}

function parse_group {
    echo $1 | sed 's/^.*://' | tr ',' '\n' | sort
}

if [ $# -lt 2 ]; then
    print_usage
    exit 1
fi

VERBOSE=false

while getopts ":hv" opt; do
    case $opt in
    h) 
        print_usage
        exit
        ;;
    v) 
        VERBOSE=true
        shift
        ;;
    \?)
        print_usage
        exit 1
        ;;
    esac
done

Gs=( $@ )
TMP=$(mktemp)
Nprev=0

for G in ${Gs[@]}; do
    RAW=$(getent group $G)
    if [ $? -ne 0 ]; then
        echo "Error: cannot find group $G"
        rm $TMP
        exit 1
    fi

    parse_group $RAW >>$TMP

    if $VERBOSE; then
        N=$(wc -l <$TMP)
        N=$((N-Nprev))
        Nprev=$N
        echo "$G ($N):"
        tail -n $N $TMP | tr '\n' ' '
        echo
        echo
    fi
done

INT=( $(sort $TMP | uniq -c | awk -v n=${#Gs[@]} '{if ($1==n) print $2}') )
if $VERBOSE; then
    echo "Intersection (${#INT[@]}):"
fi
echo ${INT[@]}

rm $TMP
