#!/bin/bash
# list storage by school
# Ruoshi Sun
# 2020-10-19

# parse argument
case $1 in
    CLAS|SDS|SEAS|SOM)
        ARG=$1
        PRINT_ALL=false
        ;;
    all) 
        PRINT_ALL=true
        ;;
    *)
        echo "Usage: `basename $0` CLAS|SDS|SEAS|SOM"
        exit 1
        ;;
esac

function parse_ldap {
    FIELD=$1
    FILE=$2
    if [ "$FIELD" = "displayName" ]; then
        sed -n "s/^$FIELD: //p" $FILE | tr ' ' '_'
    elif [ "$FIELD" = "uvaDisplayDepartment" ]; then
        sed -n "s/^$FIELD: [^:]*://p" $FILE | tail -1 | tr ' ' '_'
    else
        echo "Unknown field $FIELD"
        exit 1
    fi
}

total_size=0
total_used=0

TMP=$(mktemp)
#echo $TMP
TMPLDAP=$(mktemp)
LOG=storage.log

IN=(/nv/vol188/dtn/qumulo-list /nv/vol188/dtn/sammas-list)
TYPES=(project value)
DIRS=(project nv)

#printf "%-10s %-40s %-8s %-35s %-25s %-10s %-10s\n" School Department Username Name Volume "Size (TB)" "Used (TB)" >$LOG
printf "%-6s %-8s %-35s %-25s %-8s %-10s %-10s\n" School Username Name Volume Type "Size (TB)" "Used (TB)" >$LOG
printf "%0.s-" {1..107} >>$LOG
echo >>$LOG

for i in ${!IN[@]}; do
    #echo ${IN[$i]}
    {
        TYPE=${TYPES[$i]}
        DIR=${DIRS[$i]}
        read # skip first line
        while read -r line; do
            USERNAME=`echo $line|awk -F: '{print $8}'`
            VOLUME=`echo $line|awk -F: '{print $1}'`

            if [ ! -e /$DIR/$VOLUME ]; then
                continue
            fi

# skip instructional
            RAWSIZE=$(echo $line|awk -F: '{print $4}')
            if [[ "$RAWSIZE" == "50GB" || "$RAWSIZE" == "10GB" ]]; then
                continue
            fi

            ldapsearch -x -LLL -h ldap.virginia.edu -b "o=University of Virginia,c=US" uid=$USERNAME >$TMPLDAP
            NAME=$(parse_ldap displayName $TMPLDAP)
            SCHOOL_DEPT=$(parse_ldap uvaDisplayDepartment $TMPLDAP)

# deal with school & department
            case "${SCHOOL_DEPT%-*}" in
                "AS"|"Arts_&_Sciences_Graduate")
                    SCHOOL=CLAS ;;
                "DS"|"Data_Science"|"Data_Science_Graduate")
                    SCHOOL=SDS ;;
                "EN"|"Engineering_Graduate")
                    SCHOOL=SEAS ;;
                "MD"|"Medicine")
                    SCHOOL=SOM ;;
                *)
                    #>&2 echo "$USERNAME $SCHOOL_DEPT"
                    continue
                    ;;
            esac

            if [ "$PRINT_ALL" = "false" ]; then
                if [ ! "$SCHOOL" = "$ARG" ]; then
                    continue
                fi
            fi

            printf "%-6s %-8s %-35s %-25s %-8s" $SCHOOL $USERNAME $NAME $VOLUME $TYPE

            df /$DIR/$VOLUME | awk '
            function KtoT(input) {
                return input/1024**3
            } {
                if (NR==2) {
                    size=KtoT($2)
                    used=KtoT($3)
                    printf "%10.4f %10.4f\n",size,used
                }
            }'
        done
    } < ${IN[$i]} >> $TMP
done

rm $TMPLDAP

sort -k1 $TMP >>$LOG

awk '{
    size+=$6
    used+=$7
} END {
    printf "Total size: %.4f TB\n", size
    printf "Total used: %.4f TB (%.4f%%)\n", used, used/size*100
}' $TMP

rm $TMP
