#!/bin/bash
# compile node info
# Ruoshi Sun
# 2021-03-09

ALL_NAME=()
ALL_CORE=()
ALL_MEMORY=()
ALL_NUMNODE=()
ALL_GPUNAME=()
ALL_GPUMEMORY=()
ALL_GPU=()

function getval {
    echo "$1" | awk -v s=$2 -F'=' '$0~s {print $NF}'
}

function append {
    for i in ${!ALL_NAME[@]}; do
        if [ "$1" = "${ALL_NAME[$i]}" ]; then
            ALL_NUMNODE[$i]=$((${ALL_NUMNODE[$i]}+1))
            return
        fi
    done

    ALL_NAME+=("$1")
    ALL_CORE+=("$2")
    ALL_MEMORY+=("$3")
    ALL_GPUNAME+=("$4")
    ALL_GPUMEMORY+=("$5")
    ALL_GPU+=("$6")
    ALL_NUMNODE+=(1)
}

function report {
# put GPU nodes at the bottom
# print memory in GB
# replace KNL's 256 with 64 physical cores
# RTX2080 -> RTX 2080 Ti
    echo "Cores/Node,Memory/Node (GB),GPU model,GPU memory/Device (GB),GPU devices/Node,# of Nodes"
    for i in ${!ALL_NAME[@]}; do
        printf -- "%d,%d,%s,%s,%s,%s\n" \
            "${ALL_CORE[$i]}" "$((ALL_MEMORY[$i]/1000))" \
            "${ALL_GPUNAME[$i]}" "${ALL_GPUMEMORY[$i]}" "${ALL_GPU[$i]}" \
            "${ALL_NUMNODE[$i]}"
    done | sort -t, -k3 | sed -e 's/^256,/64,/' -e 's/RTX2080/RTX 2080 Ti/g'
}

NODES=($(scontrol show hostnames $(sinfo -ho "%N")))
NUM_NODES=${#NODES[@]}

for i in ${!NODES[@]}; do
    echo -ne "$((i+1))/$NUM_NODES\r"
    NODE=${NODES[$i]}

    INFO=$(scontrol show node $NODE -o | tr ' ' '\n')
    CORE=$(getval "$INFO" CPUTot)
    MEMORY=$(getval "$INFO" RealMemory)
    PARTITION=$(getval "$INFO" Partitions)

    if [[ "$PARTITION" = "gpu" || "$PARTITION" = "bii-gpu" ]]; then
        GPUNAME=$(getval "$INFO" AvailableFeatures)
        GPUNAME=${GPUNAME^^}
        GPU=$(getval "$INFO" CfgTRES)

# hardcode GPU memory
        case $GPUNAME in
        K80)
            GPUMEMORY="11"
            ;;
        P100)
            GPUMEMORY="12"
            ;;
        RTX2080)
            GPUMEMORY="11"
            ;;
        V100)
            if [ "$CORE" = "40" ]; then
                GPUMEMORY="32"
            else
                GPUMEMORY="16"
            fi
            ;;
        esac
    else
        GPUNAME="-"
        GPUMEMORY="-"
        GPU="-"
    fi

    NAME="${CORE}_${MEMORY}_${GPUNAME}"

    append $NAME $CORE $MEMORY $GPUNAME $GPUMEMORY $GPU
    count=$((count+1))
done

echo
report >nodeinfo.csv
