#!/bin/bash
# generate OOD session URL
if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` JobID"
    exit 1
fi
JOBID=$1

JOBINFO=$(scontrol show job $1)
if [ $? -ne 0 ]; then
    echo "$JOBID is not an active job"
    exit 1
fi

USERNAME=$(echo "$JOBINFO" | sed -n 's/^\s*UserId=\([a-z0-9]*\)(.*$/\1/p')
DIR=$(echo "$JOBINFO" | awk -F= '/WorkDir/ {print $2}')
echo "$DIR"

# check if job is an OOD session
if [[ ! "$DIR" =~ "/home/$USERNAME/ondemand".* ]]; then
    echo "Not an OOD session"
    exit 1
fi

CONNECTION=$(sudo su - $USERNAME -c "cat $DIR/connection.yml")
HOST=$(echo "$CONNECTION" | awk 'NR==1 {print $2}')
PORT=$(echo "$CONNECTION" | awk 'NR==2 {print $2}')
PASSWORD=$(echo "$CONNECTION" | awk 'NR==3 {print $2}')
APP=$(basename $(realpath $DIR/../..))

case $APP in
uva_matlab)
    URL="https://rivanna-portal.hpc.virginia.edu/pun/sys/dashboard/noVNC-1.0.0/vnc.html?utf8=%E2%9C%93&autoconnect=true&path=rnode%2F$HOST%2F$PORT%2Fwebsockify&resize=remote&compressionsetting=6&qualitysetting=2&commit=Launch+MATLAB"
    ;;
*)
    URL="https://rivanna-portal.hpc.virginia.edu/node/$HOST/$PORT/lab"
    ;;
esac

echo $URL
echo $PASSWORD
