#!/bin/bash
# generate OOD session URL
if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` JobID"
    exit 1
fi
JOBID=$1
TMP=$(mktemp)

scontrol show job $1 >$TMP
if [ $? -ne 0 ]; then
    echo "$JOBID is not an active job"
    rm $TMP
    exit 1
fi

USERNAME=$(sed -n 's/^\s*UserId=\([a-z0-9]*\)(.*$/\1/p' $TMP)
DIR=$(awk -F= '/WorkDir/ {print $2}' $TMP)
echo "$DIR"

# check if job is an OOD session
if [[ ! "$DIR" =~ "/home/$USERNAME/ondemand".* ]]; then
    echo "Not an OOD session"
    rm $TMP
    exit 1
fi

sudo su - $USERNAME -c "cat $DIR/connection.yml" >$TMP
HOST=$(awk 'NR==1 {print $2}' $TMP)
PORT=$(awk 'NR==2 {print $2}' $TMP)
PASSWORD=$(awk 'NR==3 {print $2}' $TMP)
APP=$(basename $(realpath $DIR/../..))

case $APP in
uva_matlab)
    URL="https://rivanna-portal.hpc.virginia.edu/pun/sys/dashboard/noVNC-1.0.0/vnc.html?utf8=%E2%9C%93&autoconnect=true&path=rnode%2F$HOST%2F$PORT%2Fwebsockify&resize=remote&compressionsetting=6&qualitysetting=2&commit=Launch+MATLAB"
    ;;
*)
    URL="https://rivanna-portal.hpc.virginia.edu/node/$HOST/$PORT/lab"
    ;;
esac

echo $URL
echo $PASSWORD

rm $TMP
